# PostgreSQL

development:
  adapter: postgresql
  encoding: unicode
  database: bradleylopez_development
  pool: 5
  host: localhost
  timeout: 5000


test:
  adapter: postgresql
  encoding: unicode
  database: bradleylopez_test
  pool: 5
  timeout: 5000